#!/usr/bin/env python3
"""Reject private or machine-local content before this repository is published."""

from __future__ import annotations

import hashlib
import os
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MAX_TEXT_BYTES = 5 * 1024 * 1024

# These files are generated by scripts/generate_audio_fixtures.py.  Keeping the
# hashes here makes the exception narrow: replacing one with real audio fails.
SYNTHETIC_WAVS = {
    "tests/fixtures/audio/boundary_impulses.wav": (
        768_044,
        "ba96c9d0ee9f09040f7386e77ec60fc453592b469bcb32cb2dce3cd9a9789187",
    ),
    "tests/fixtures/audio/candidate_delayed_minus6db.wav": (
        768_044,
        "c04cd63c2d9cec098e5e4ed28296539d7a3899ebc9fb19cb5f0210ef8b6c8785",
    ),
    "tests/fixtures/audio/reference_mix.wav": (
        768_044,
        "6fd033b2cb07e1388dddafccfbc4e9665d5c67864397c6acd13587dcc849c3e3",
    ),
}

FORBIDDEN_DIRECTORY_NAMES = {
    ".claude",
    ".fl-studio-mcp-locks",
    ".idea",
    ".private",
    ".pytest_cache",
    ".vscode",
    "__pycache__",
    "artifacts",
    "bounces",
    "build",
    "dist",
    "renders",
}
# Private working documents whose names have carried project-identifying
# content. docs/plugin-support.md is the public, contributor-maintained
# compatibility table and is deliberately not one of these.
FORBIDDEN_EXACT_PATHS = {
    ".ds_store",
    ".mcp.json",
    "docs/current-status.md",
    "docs/plugin-coverage.md",
    "docs/plugin-insertion.md",
    "handoff.md",
}
PRIVATE_SUFFIXES = {
    ".aac",
    ".aif",
    ".aiff",
    ".caf",
    ".flac",
    ".flp",
    ".fst",
    ".m4a",
    ".mid",
    ".midi",
    ".mp3",
    ".oga",
    ".ogg",
    ".rf64",
    ".w64",
    ".wav",
    ".wave",
}


def _pieces(*values: bytes) -> bytes:
    """Build scanner signatures without making the source match itself."""

    return b"".join(values)


CONTENT_PATTERNS = (
    ("absolute macOS home path", re.compile(_pieces(b"/", b"Users", b"/") + rb"[^/\s]+/")),
    ("absolute Linux home path", re.compile(_pieces(b"/", b"home", b"/") + rb"[^/\s]+/")),
    (
        "absolute Windows home path",
        re.compile(rb"[A-Za-z]:[\\/]Users[\\/][^\\/\s]+[\\/]", re.I),
    ),
    (
        "private key material",
        re.compile(_pieces(b"-----BEGIN ", b"PRIVATE KEY-----")),
    ),
    ("GitHub token", re.compile(rb"\bghp_[A-Za-z0-9]{20,}\b")),
    ("GitHub token", re.compile(rb"\bgithub_pat_[A-Za-z0-9_]{20,}\b")),
    ("AWS access key", re.compile(rb"\bAKIA[0-9A-Z]{16}\b")),
)


def public_candidates() -> list[Path]:
    """Return tracked files plus non-ignored files that could be committed."""

    process = subprocess.run(
        ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
        cwd=ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if process.returncode:
        detail = process.stderr.decode(errors="replace").strip()
        raise RuntimeError(f"git ls-files failed: {detail}")
    return sorted(Path(os.fsdecode(value)) for value in process.stdout.split(b"\0") if value)


def check_file(relative: Path) -> list[str]:
    failures: list[str] = []
    relative_text = relative.as_posix()
    relative_folded = relative_text.casefold()
    path = ROOT / relative

    if path.is_symlink():
        return ["symbolic links are not allowed in the public tree"]
    if not path.is_file():
        return failures

    parts = {part.casefold() for part in relative.parts[:-1]}
    blocked_parts = sorted(parts & FORBIDDEN_DIRECTORY_NAMES)
    if blocked_parts:
        failures.append(f"forbidden directory: {blocked_parts[0]}")
    if relative_folded in FORBIDDEN_EXACT_PATHS:
        failures.append("forbidden private or release-process file")

    name_folded = relative.name.casefold()
    if name_folded == ".env" or (
        name_folded.startswith(".env.") and name_folded != ".env.example"
    ):
        failures.append("environment file may contain secrets")
    if relative.suffix.casefold() in {".key", ".p12", ".pem", ".pfx"}:
        failures.append("credential file extension")

    expected_wav = SYNTHETIC_WAVS.get(relative_text)
    if relative.suffix.casefold() in PRIVATE_SUFFIXES:
        if expected_wav is None:
            failures.append("project or media file is not an approved synthetic fixture")
            return failures
        expected_size, expected_digest = expected_wav
        content = path.read_bytes()
        digest = hashlib.sha256(content).hexdigest()
        if len(content) != expected_size or digest != expected_digest:
            failures.append("synthetic WAV fixture does not match its pinned size and SHA-256")
        return failures

    content = path.read_bytes()
    if len(content) > MAX_TEXT_BYTES:
        failures.append(f"unexpected file larger than {MAX_TEXT_BYTES} bytes")
        return failures
    if b"\0" in content:
        failures.append("unexpected binary file")
        return failures
    for label, pattern in CONTENT_PATTERNS:
        if pattern.search(content):
            failures.append(label)
    return failures


def main() -> int:
    try:
        candidates = public_candidates()
    except RuntimeError as error:
        print(f"public-tree check could not run: {error}", file=sys.stderr)
        return 2

    failures: list[tuple[Path, str]] = []
    candidate_names = {path.as_posix() for path in candidates}
    for fixture in sorted(set(SYNTHETIC_WAVS) - candidate_names):
        failures.append((Path(fixture), "required synthetic WAV fixture is missing"))
    for relative in candidates:
        failures.extend((relative, reason) for reason in check_file(relative))

    if failures:
        print("Public-tree privacy check failed:", file=sys.stderr)
        for relative, reason in failures:
            print(f"  {relative.as_posix()}: {reason}", file=sys.stderr)
        return 1

    print(f"Public-tree privacy check passed ({len(candidates)} files checked).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
